# --- Shared config for BOTH leaders in the multi-leader POC ---
listen_addresses = '*'
port = 5432

# LOGICAL replication is REQUIRED for multi-leader (row-level pub/sub).
# Physical/streaming replication cannot be multi-master (standbys are read-only).
wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_logical_replication_workers = 10
hot_standby = on

hba_file = '/etc/postgresql/pg_hba.conf'
